name: cbioportal-performance-test
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_publish_docker_image: # TODO rename if this is one big job
    if: github.repository == 'cbioportal/cbioportal' && !contains(github.event.pull_request.labels.*.name, 'api-error')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1
      - name: Extract PR number
        # create the docker image tag by extracting pr number from github
        run: echo "##[set-output name=image_tag;]$(export set GITHUB_REF_TMP=${GITHUB_REF#refs/pull/};echo cbioportal-performance-test-${GITHUB_REF_TMP%/merge})"
        id: extract_tags
      - name: Rename deployment
        run: |
         sed "s/cbioportal-performance-test\b/${{ steps.extract_tags.outputs.image_tag }}/g" .github/k8s/cbioportal_performance_test.yaml > /tmp/cbioportal_performance_test.yaml
      - name: Docker build with cache
        uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME_PIPELINES }}"
          password: "${{ secrets.DOCKER_PASSWORD_PIPELINES }}"
          image_name: cbioportalpipelines/cbioportal
          image_tag: ${{ steps.extract_tags.outputs.image_tag }}
          context: .
          dockerfile: docker/web/Dockerfile
          pull_image_and_stages: false
      - name: Set context for kubectl cluster
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Deploy to kubernetes
        uses: Azure/k8s-deploy@v1.2
        with:
          manifests: |
            /tmp/cbioportal_performance_test.yaml
          images: 'cbioportalpipelines/cbioportal:${{ steps.extract_tags.outputs.image_tag }}'
          action: deploy
          kubectl-version: 'v1.14.0'
      - name: Extract pod name
        run: echo "##[set-output name=pod_name;]$(kubectl get pods --selector=run=${{ steps.extract_tags.outputs.image_tag }} | tail -1| cut -f1 -d' ')"
        id: extract_pod_name
      - name: Install curl
        run: |
            kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "apt-get update; apt-get -y install curl; apt-get -y install jq;"
      - name: POST Request for /filtered-samples endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/filtered-samples/fetch"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"genie_public\" ]}' | jq --join-output --compact-output '[.[]|{sampleId: .\"sampleId\", studyId: \"genie_public\"}]' > samples.json; jq --join-output --compact-output '{sampleIdentifiers: [.[]]}' samples.json > sampleIdentifiers.json"
      - name: POST Request for /cna-genes endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/cna-genes/fetch"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "entrezGeneId"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
                    echo "Response did not contain search string '$SEARCH_STR'"
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /treatments/patient endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/treatments/patient"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                # TODO: change if treatment data is ever added
                if [ "$RESPONSE_BODY" != "$EMPTY_LIST_RESPONSE" ]; then
                    echo "Request returned a non-empty response when we expect an empty list."
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /treatments/sample endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/treatments/sample"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                # TODO: change if treatment data is ever added
                if [ "$RESPONSE_BODY" != "$EMPTY_LIST_RESPONSE" ]; then
                    echo "Request returned a non-empty response when we expect an empty list."
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /fusion-genes/fetch endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/fusion-genes/fetch"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "entrezGeneId"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
                    echo "Response did not contain search string '$SEARCH_STR'"
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /copy-number-segments/fetch endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/copy-number-segments/fetch?projection=META"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "seg"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@samples.json'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ]; then
                echo "Request failed with empty list when we expected it to be empty."
                exit 1
            else
                if [[ ! -z "$RESPONSE_BODY" ]]; then 
                    # TODO: study view is querying with projection=META which does not return anything
                    # update if we ever use a query that reutrns data (e.g SUMMARY)
                    echo "Request returned a non-empty response when we expect an empty response."
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /clinical-data-bin-counts endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/clinical-data-bin-counts/fetch?dataBinMethod=STATIC"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "MUTATION_COUNT"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"attributes\":[{\"attributeId\":\"MUTATION_COUNT\",\"disableLogScale\":false},{\"attributeId\":\"FRACTION_GENOME_ALTERED\",\"disableLogScale\":false},{\"attributeId\":\"AGE_AT_SEQ_REPORT\",\"disableLogScale\":false},{\"attributeId\":\"AGE_AT_SEQ_REPORT_DAYS\",\"disableLogScale\":false},{\"attributeId\":\"INT_CONTACT\",\"disableLogScale\":false},{\"attributeId\":\"INT_DOD\",\"disableLogScale\":false},{\"attributeId\":\"SEQ_YEAR\",\"disableLogScale\":false}],\"studyViewFilter\":{\"studyIds\":[\"genie_public\"],\"patientTreatmentFilters\":{\"filters\":[]},\"sampleTreatmentFilters\":{\"filters\":[]}}}'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
                    echo "Response did not contain search string '$SEARCH_STR'"
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /clinical-data-counts endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/clinical-data-counts/fetch"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "SAMPLE_COUNT"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"attributes\":[{\"attributeId\":\"CANCER_TYPE\"},{\"attributeId\":\"CANCER_TYPE_DETAILED\"},{\"attributeId\":\"SAMPLE_COUNT\"},{\"attributeId\":\"SEX\"},{\"attributeId\":\"ETHNICITY\"},{\"attributeId\":\"SAMPLE_TYPE\"},{\"attributeId\":\"CENTER\"},{\"attributeId\":\"ONCOTREE_CODE\"},{\"attributeId\":\"PRIMARY_RACE\"},{\"attributeId\":\"SAMPLE_TYPE_DETAILED\"},{\"attributeId\":\"SECONDARY_RACE\"},{\"attributeId\":\"SEQ_ASSAY_ID\"},{\"attributeId\":\"TERTIARY_RACE\"}],\"studyViewFilter\":{\"studyIds\":[\"genie_public\"],\"patientTreatmentFilters\":{\"filters\":[]},\"sampleTreatmentFilters\":{\"filters\":[]}}}'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
                    echo "Response did not contain search string '$SEARCH_STR'"
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /clinical-data-density-plot endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "http://localhost:8888/api/clinical-data-density-plot/fetch?xAxisAttributeId=FRACTION_GENOME_ALTERED&xAxisBinCount=50&xAxisEnd=1&xAxisStart=0&yAxisAttributeId=MUTATION_COUNT&yAxisBinCount=52&yAxisStart=0"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "count"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
                    echo "Response did not contain search string '$SEARCH_STR'"
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: POST Request for /mutated-genes endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180 
          URL: "http://localhost:8888/api/mutated-genes/fetch"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "entrezGeneId"
        run: |
          sh ./.github/k8s/curl.sh ${{ steps.extract_pod_name.outputs.pod_name }} 300 genie_public $URL 
          #kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"genie_public\" ]}'" > curl.out
          #RESPONSE_CODE=`tail -1 curl.out`
          #RESPONSE_BODY=`head -1 curl.out`
          #if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
          #  echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
          #  exit 1
          #else
          #  if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
          #      echo "Request failed with empty response"
          #      exit 1
          #  else
          #      if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
          #          echo "Response did not contain search string '$SEARCH_STR'"
          #          exit 1
          #      fi
          #  fi
          #  exit 0
          #fi
      - name: POST Request for /sample-list-counts endpoint
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180 
          URL: "http://localhost:8888/api/sample-lists-counts/fetch"
          OK_RESPONSE_CODE: 200
          EMPTY_LIST_RESPONSE: "[]"
          SEARCH_STR: "count"
        run: |
          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"sampleTreatmentFilters\":{\"filters\":[]},\"patientTreatmentFilters\":{\"filters\":[]},\"studyIds\":[\"genie_public\"]}'" > curl.out
          RESPONSE_CODE=`tail -1 curl.out`
          RESPONSE_BODY=`head -1 curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
                echo "Request failed with empty response"
                exit 1
            else
                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
                    echo "Response did not contain search string '$SEARCH_STR'"
                    exit 1
                fi
            fi
            exit 0
          fi
      - name: Delete pod
        if: ${{ always() }}
        run: |
          kubectl delete -f /tmp/cbioportal_performance_test.yaml
      - name: DELETE request to dockerhub
        if: ${{ always() }}
        env:
          MAX_WAIT_TIME_IN_SECONDS: 180
          URL: "https://hub.docker.com/v2/repositories/cbioportalpipelines/cbioportal/tags/${{ steps.extract_tags.outputs.image_tag }}/"
          OK_RESPONSE_CODE: 204

        # DELETE request to URL with a MAX_WAIT_TIME_IN_SECONDS second limit
        #   if curl fails, automatically exit with curl's non-zero exit code
        #   else if we did not get a OK_RESPONSE_CODE exit with a non-zero exit code
        #   else we are OK!
        run: |
          JWT_TOKEN_SECRET="`curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKER_USERNAME_PIPELINES }}'", "password": "${{ secrets.DOCKER_PASSWORD_PIPELINES }}"}' https://hub.docker.com/v2/users/login/ | sed 's/.*token": "//' | sed 's/"}//'`"
          echo ${JWT_TOKEN_SECRET}
          
          echo "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -o /dev/null -w '%{http_code}' -X DELETE -H 'Authorization: JWT ${JWT_TOKEN_SECRET}' '$URL'"
          
          curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: JWT ${JWT_TOKEN_SECRET}" "$URL" > curl.out
          RESPONSE_CODE=`cat curl.out`
          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
            exit 1
          else
            echo "Request succeeded with expected response code '$OK_RESPONSE_CODE'"
            exit 0
          fi

# Reference: https://github.com/marketplace/actions/build-docker-images-using-cache
